In [10]:
import numpy as np
a = np.arange(12).reshape(3,4) + 1
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
mask = a < 7
mask

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [12]:
a[mask][np.array([3, 0, 4])]

array([4, 1, 5])

In [13]:
inf = float('inf')

In [14]:
inf - 1e100

inf

In [15]:
1/inf

0.0

In [16]:
np.exp(-inf)

0.0

In [17]:
10e500

inf

In [18]:
a = np.arange(12).reshape(2,3,4)
np.argmax(a, axis=0)

array([2, 2, 2, 2])